Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Models/ErrorViewModel.cs
namespace WebDay2021.SignalR.SimpleFruitShop.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Models/HomeIndexViewModel.cs
using System.Collections.Generic;

namespace WebDay2021.SignalR.SimpleFruitShop.WebApp.Models
{
    public class HomeIndexViewModel
    {
        public List<ChartItem> AvailableProducts { get; set; }

        public class ChartItem
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public decimal PricePerKg { get; set; }

            public int QuantityInKg { get; set; }
        }
    }
}

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Models/SalesMonitorIndexViewModel.cs
using System.Collections.Generic;

namespace WebDay2021.SignalR.SimpleFruitShop.WebApp.Models
{
    public class SalesMonitorIndexViewModel
    {
        public List<SoldProduct> Products { get; set; }

        public class SoldProduct
        {
            public int Id { get; set; }
            
            public string Name { get; set; }

            public int TotalKgSold { get; set; }

            public int TotalRevenue { get; set; }
        }
    }
}

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebDay2021.SignalR.SimpleFruitShop.WebApp.Data;
using WebDay2021.SignalR.SimpleFruitShop.WebApp.Hubs;
using WebDay2021.SignalR.SimpleFruitShop.WebApp.Models;

namespace WebDay2021.SignalR.SimpleFruitShop.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IHubContext<MonitorHub> _hubContext;

        public HomeController(ILogger<HomeController> logger, IHubContext<MonitorHub> hubContext)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _hubContext = hubContext ?? throw new ArgumentNullException(nameof(hubContext));
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new HomeIndexViewModel()
            {
                AvailableProducts = Inventory.AvailableItems.Select(i => new HomeIndexViewModel.ChartItem()
                {
                    Id = i.Id,
                    Name = i.Name,
                    PricePerKg = i.PricePerKg
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(HomeIndexViewModel model)
        {
            foreach (var soldProduct in model.AvailableProducts.Where(p => p.QuantityInKg > 0))
            {
                await _hubContext.Clients.All.SendAsync("ProductSold", soldProduct.Id, soldProduct.QuantityInKg, soldProduct.PricePerKg);
            }

            return RedirectToAction(nameof(HomeController.Index));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Controllers/SalesMonitorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebDay2021.SignalR.SimpleFruitShop.WebApp.Data;
using WebDay2021.SignalR.SimpleFruitShop.WebApp.Models;

namespace WebDay2021.SignalR.SimpleFruitShop.WebApp.Controllers
{
    [Authorize]
    public class SalesMonitorController : Controller
    {
        public IActionResult Index()
        {
            var model = new SalesMonitorIndexViewModel()
            {
                Products = Inventory.AvailableItems.Select(i => new SalesMonitorIndexViewModel.SoldProduct()
                {
                    Id = i.Id,
                    Name = i.Name
                }).ToList()
            };

            return View(model);
        }

        [AllowAnonymous]
        public IActionResult IndexAnonymous()
        {
            var model = new SalesMonitorIndexViewModel()
            {
                Products = Inventory.AvailableItems.Select(i => new SalesMonitorIndexViewModel.SoldProduct()
                {
                    Id = i.Id,
                    Name = i.Name
                }).ToList()
            };

            return View("Index", model);
        }
    }
}

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Views/Home/Index.cshtml
@model WebDay2021.SignalR.SimpleFruitShop.WebApp.Models.HomeIndexViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<form asp-controller="Home" asp-action="Index" method="post">
    <table class='table table-striped' aria-labelledby="tableLabel" *ngIf="forecasts">
        <thead>
            <tr>
                <th>Prodotto</th>
                <th>Prezzo al Kg. (€)</th>
                <th>Quantità Desiderata (Kg.)</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.AvailableProducts.Count(); i++)
            {
                <tr>
                    @Html.EditorFor(model => model.AvailableProducts[i])
                </tr>
            }
        </tbody>
    </table>
    <button type="submit">Acquista</button>
</form>

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Views/SalesMonitor/Index.cshtml
@model WebDay2021.SignalR.SimpleFruitShop.WebApp.Models.SalesMonitorIndexViewModel

@{
    ViewData["Title"] = "Sales Monitor";
}

<div class="text-center">
    <h1 class="display-4">Web Day 2021 - Simple Fruit Shop : Sales Monitor</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<table class='table table-striped' aria-labelledby="tableLabel" *ngIf="forecasts">
    <thead>
        <tr>
            <th>Prodotto</th>
            <th>Totale Venduto (Kg.)</th>
            <th>Totale Ricavo (€)</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Products.Count(); i++)
        {
             @Html.DisplayFor(model => model.Products[i])
        }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript" src="~/lib/microsoft-signalr/signalr.min.js"></script>
    <script type="text/javascript" src="~/lib/msgpack5/msgpack5.min.js"></script>
    <script type="text/javascript" src="~/lib/microsoft/signalr-protocol-msgpack/dist/browser/signalr-protocol-msgpack.min.js"></script>
    <script type="text/javascript">
        (async function () {
            const connection = new signalR.HubConnectionBuilder()
                .withAutomaticReconnect()
                // .withHubProtocol(new signalR.protocols.msgpack.MessagePackHubProtocol())
                .withUrl('/admin/salesmonitor')
                .build();

            connection.on('ProductSold', (id, quantityInKg, pricePerKg) => {
                let tableRow = document.getElementById(`product-${id}`);

                let totalKgSoldColumn = tableRow.getElementsByClassName(`product-kg-sold`)[0];
                let totalRevenueColumn = tableRow.getElementsByClassName(`product-total-revenue`)[0];

                totalKgSoldColumn.innerHTML = (parseInt(totalKgSoldColumn.innerHTML) + quantityInKg).toString();
                totalRevenueColumn.innerHTML = (parseFloat(totalRevenueColumn.innerHTML) + pricePerKg * quantityInKg).toFixed(2);
            });

            try {
                await connection.start();
            } catch (err) {
                alert('Error, can\'t open the Hub connection!');
            }
        })();
    </script>
} 

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Views/Shared/DisplayTemplates/SoldProduct.cshtml
@model SalesMonitorIndexViewModel.SoldProduct

<tr id="product-@Model.Id">
    <td>
        <span>@Model.Name</span>
        <br />
        <img src="~/img/@(Model.Id).png" height="50" />
    </td>
    <td class="product-kg-sold">
        @Model.TotalKgSold
    </td>
    <td class="product-total-revenue">
        @Model.TotalRevenue
    </td>
</tr>

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Views/Shared/EditorTemplates/ChartItem.cshtml
@model HomeIndexViewModel.ChartItem

<td>
    <input asp-for="@Model.Id" type="hidden" />
    <input asp-for="@Model.Name" type="hidden" />
    <span>@Html.DisplayFor(model => model.Name)</span>
    <br />
    <img src="~/img/@(Model.Id).png" height="50" />
</td>
<td>
    <input asp-for="@Model.PricePerKg" type="hidden" />
    @Html.DisplayFor(model => model.PricePerKg)
</td>
<td>
    <input asp-for="@Model.QuantityInKg" />
</td>

Demo/WebDay2021.SignalR.SimpleFruitShop/WebDay2021.SignalR.SimpleFruitShop.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Web Day 2021 - Simple Fruit Shop : @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web Day 2021 - Simple Fruit Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesMonitor" asp-action="Index">Monitor Sales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesMonitor" asp-action="IndexAnonymous">Monitor Sales (no auth)</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebDay2021.SignalR.SimpleFruitShop.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>